# Setting Linux is forcing th extension to be .o instead of .obj when building on WIndows.
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

# ============================================================
# 优先查找项目本地 tools/ 目录，没找到则 fallback 到系统 PATH
# ============================================================
get_filename_component(_CMAKE_PROJ_ROOT "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)

set(_LOCAL_GCC "${_CMAKE_PROJ_ROOT}/tools/arm-gcc/bin")
if(EXISTS "${_LOCAL_GCC}/arm-none-eabi-gcc.exe")
    set(CMAKE_C_COMPILER       "${_LOCAL_GCC}/arm-none-eabi-gcc.exe")
    set(CMAKE_CXX_COMPILER     "${_LOCAL_GCC}/arm-none-eabi-g++.exe")
    set(CMAKE_ASM_COMPILER     "${_LOCAL_GCC}/arm-none-eabi-gcc.exe")
    set(CMAKE_LINKER           "${_LOCAL_GCC}/arm-none-eabi-g++.exe")
    set(CMAKE_AR               "${_LOCAL_GCC}/arm-none-eabi-gcc-ar.exe")
    set(CMAKE_CXX_COMPILER_AR  "${_LOCAL_GCC}/arm-none-eabi-gcc-ar.exe")
    set(CMAKE_C_COMPILER_AR    "${_LOCAL_GCC}/arm-none-eabi-gcc-ar.exe")
    message(STATUS "GCC: found locally at ${_LOCAL_GCC}")
else()
    find_program(CMAKE_C_COMPILER   NAMES arm-none-eabi-gcc)
    find_program(CMAKE_CXX_COMPILER NAMES arm-none-eabi-g++ arm-none-eabi-g++)
    find_program(CMAKE_ASM_COMPILER NAMES arm-none-eabi-gcc)
    find_program(CMAKE_AR           NAMES arm-none-eabi-gcc-ar)
    find_program(CMAKE_CXX_COMPILER_AR NAMES arm-none-eabi-gcc-ar)
    find_program(CMAKE_C_COMPILER_AR   NAMES arm-none-eabi-gcc-ar)
    find_program(CMAKE_LINKER      NAMES arm-none-eabi-g++ arm-none-eabi-g++)
    message(STATUS "GCC: found from PATH")
endif()
unset(_LOCAL_GCC)
unset(_CMAKE_PROJ_ROOT)

SET(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
SET(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
SET(CMAKE_C_OUTPUT_EXTENSION .o)
SET(CMAKE_CXX_OUTPUT_EXTENSION .o)
SET(CMAKE_ASM_OUTPUT_EXTENSION .o)
SET(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> -crs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> -crs <TARGET> <LINK_FLAGS> <OBJECTS>")

set(GCC ON)

if(NOT ARM_CPU)
    set(ARM_CPU "cortex-a5" CACHE STRING "Set ARM CPU. Default : cortex-a5")
endif()

if (ARM_CPU STREQUAL "cortex-m55")
  SET(CMAKE_C_FLAGS "-march=armv8.1-m.main+mve.fp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_CXX_FLAGS "-march=armv8.1-m.main+mve.fp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_ASM_FLAGS "-march=armv8.1-m.main+mve.fp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_EXE_LINKER_FLAGS "-fno-use-linker-plugin -march=armv8.1-m.main+mve.fp+fp.dp" CACHE INTERNAL "")
elseif (ARM_CPU STREQUAL "cortex-m55+nomve.fp+nofp")
  SET(CMAKE_C_FLAGS "-march=armv8.1-m.main+dsp+nofp" CACHE INTERNAL "")
  SET(CMAKE_CXX_FLAGS "-march=armv8.1-m.main+dsp+nofp" CACHE INTERNAL "")
  SET(CMAKE_ASM_FLAGS "-march=armv8.1-m.main+dsp+nofp" CACHE INTERNAL "")
  SET(CMAKE_EXE_LINKER_FLAGS "-fno-use-linker-plugin -march=armv8.1-m.main+dsp+nofp" CACHE INTERNAL "")
elseif (ARM_CPU STREQUAL "cortex-m55+nomve.fp+fp.dp")
  SET(CMAKE_C_FLAGS "-march=armv8.1-m.main+dsp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_CXX_FLAGS "-march=armv8.1-m.main+dsp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_ASM_FLAGS "-march=armv8.1-m.main+dsp+fp.dp" CACHE INTERNAL "")
  SET(CMAKE_EXE_LINKER_FLAGS "-fno-use-linker-plugin -march=armv8.1-m.main+dsp+fp.dp" CACHE INTERNAL "")
else()
  SET(CMAKE_C_FLAGS "-mcpu=${ARM_CPU}" CACHE INTERNAL "")
  SET(CMAKE_CXX_FLAGS "-mcpu=${ARM_CPU}" CACHE INTERNAL "")
  SET(CMAKE_ASM_FLAGS "-mcpu=${ARM_CPU}" CACHE INTERNAL "")
  SET(CMAKE_EXE_LINKER_FLAGS "-mcpu=${ARM_CPU}" CACHE INTERNAL "")
endif()

add_link_options("-Wl,--start-group")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
